foster_api/config/routes.rb
Rails.application.routes.draw do
  resources :messageboards
  resources :children
  resources :items, only: [:create, :index]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :sessions, only: [:create]
  resources :registrations
  delete :logout, to: "sessions#logout"
  get :logged_in, to: "sessions#logged_in"
  # root to: "static#home"
end

foster_api/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

foster_api/app/models/child.rb
class Child < ApplicationRecord
    belongs_to :user
    has_many :items
end

foster_api/app/models/item.rb
class Item < ApplicationRecord
    belongs_to :child
end

foster_api/app/models/messageboard.rb
class Messageboard < ApplicationRecord
    belongs_to :user
end

foster_api/app/models/user.rb
class User < ApplicationRecord
    has_secure_password

    has_many :children
    has_many :messageboards
    validates_presence_of :email
    validates_uniqueness_of :email
end

foster_api/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    skip_before_action :verify_authenticity_token
end

foster_api/app/controllers/children_controller.rb
class ChildrenController < ApplicationController
  before_action :set_child, only: [:show, :edit, :update, :destroy]

  # GET /children
  # GET /children.json
  def index
    @children = Child.all

    render json: @children.to_json(include: :user)
  end

  # GET /children/1
  # GET /children/1.json
  def show
    render json: @child.to_json(include: :user)
  end

  # GET /children/new
  def new
    @child = Child.new
  end

  # GET /children/1/edit
  def edit
  end

  # POST /children
  # POST /children.json
  def create
    @child = Child.new(child_params)

    respond_to do |format|
      if @child.save
        format.html { redirect_to @child, notice: 'Child was successfully created.' }
        format.json { render :show, status: :created, location: @child }
      else
        format.html { render :new }
        format.json { render json: @child.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /children/1
  # PATCH/PUT /children/1.json
  def update
    @child.update(child_params)
  end

  # DELETE /children/1
  # DELETE /children/1.json
  def destroy
    @child.destroy
    # respond_to do |format|
    #   format.html { redirect_to children_url, notice: 'Child was successfully destroyed.' }
    #   format.json { head :no_content }
    # end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_child
      @child = Child.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def child_params
      params.require(:child).permit(:name, :status, :pictures, :documents, :user_id)
    end
end

foster_api/app/controllers/concerns/current_user_concern.rb
module CurrentUserConcern
    extend ActiveSupport::Concern

    included do
        before_action :set_current_user
    end

    def set_current_user
        if session[:user_id]
            @current_user = User.find(session[:user_id])
        end
    end
    

end

foster_api/app/controllers/items_controller.rb
class ItemsController < ApplicationController
    def index
        @item = Item.all

        render json: @item.to_json(include: :child)
    end
        
    def create 
        image = Cloudinary::Uploader.upload(params[:image])
        file = Cloudinary::Uploader.upload(params[:file])
        item = Item.create(image: image["url"], child_id: params["child_id"], file: file["url"])
        render json: item
    end
end

foster_api/app/controllers/messageboards_controller.rb
class MessageboardsController < ApplicationController
  before_action :set_messageboard, only: [:show, :edit, :update, :destroy]

  # GET /messageboards
  # GET /messageboards.json
  def index
    @messageboards = Messageboard.all
  end

  # GET /messageboards/1
  # GET /messageboards/1.json
  def show
  end

  # GET /messageboards/new
  def new
    @messageboard = Messageboard.new
  end

  # GET /messageboards/1/edit
  def edit
  end

  # POST /messageboards
  # POST /messageboards.json
  def create
    @messageboard = Messageboard.new(messageboard_params)

    respond_to do |format|
      if @messageboard.save
        format.html { redirect_to @messageboard, notice: 'Messageboard was successfully created.' }
        format.json { render :show, status: :created, location: @messageboard }
      else
        format.html { render :new }
        format.json { render json: @messageboard.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /messageboards/1
  # PATCH/PUT /messageboards/1.json
  def update
    respond_to do |format|
      if @messageboard.update(messageboard_params)
        format.html { redirect_to @messageboard, notice: 'Messageboard was successfully updated.' }
        format.json { render :show, status: :ok, location: @messageboard }
      else
        format.html { render :edit }
        format.json { render json: @messageboard.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /messageboards/1
  # DELETE /messageboards/1.json
  def destroy
    @messageboard.destroy
    respond_to do |format|
      format.html { redirect_to messageboards_url, notice: 'Messageboard was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_messageboard
      @messageboard = Messageboard.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def messageboard_params
      params.require(:messageboard).permit(:subject, :content, :status)
    end
end

foster_api/app/controllers/registrations_controller.rb
class RegistrationsController < ApplicationController
    include CurrentUserConcern
    # def index
    #     @user = User.all
    
    #     render json: @user
    #   end

    def create
        user = User.create!(
            email: params['user']['email'],
            password: params['user']['password'],
            password_confirmation: params['user']['password_confirmation']
        )

        if user
            session[:user_id] = user.id
            render json: {
                status: :created,
                user: user
            }
        else
            render.json; { status: 500 }
        end

    end

    def update
        p User.find(params[:id])
        user = User.find(params[:id])
        user.update(
            email: params['user']['email'],
            password: params['user']['password'],
            password_confirmation: params['user']['password_confirmation']
        )

        # if user
        #     session[:user_id] = user.id
        #     render json: {
        #         status: :updated,
        #         user: user
        #     }
        # else
        #     render.json; { status: 500 }
        # end
        
    end
end

private
# Use callbacks to share common setup or constraints between actions.
def set_user
  @user = User.find(params[:id])
end

foster_api/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    include CurrentUserConcern
    def create
        user = User
                .find_by(email: params["user"]["email"])
                .try(:authenticate, params["user"]["password"])

        if user
            session[:user_id] = user.id
            render json: {
                status: :created,
                logged_in: true,
                user: user
            }
        else
            render.json; { status: 401 }
        end
    end

    def logged_in
        if @current_user
            render json: {
                logged_in: true,
                user: @current_user
            }
        else
            render json: {
                logged_in: false
            }
        end
    end

    def logout
        reset_session
        render json: { status: 200, logged_out: true }
    end

end

foster_api/app/controllers/static_controller.rb
class StaticController < ApplicationController
def home
    render json: { status: "It's working" }
end
end

foster_api/app/helpers/application_helper.rb
module ApplicationHelper
end

foster_api/app/helpers/children_helper.rb
module ChildrenHelper
end

foster_api/app/helpers/messageboards_helper.rb
module MessageboardsHelper
end

foster_api/app/views/children/_form.html.erb
<%= form_with(model: child, local: true) do |form| %>
  <% if child.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(child.errors.count, "error") %> prohibited this child from being saved:</h2>

      <ul>
        <% child.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :status %>
    <%= form.text_field :status %>
  </div>

  <div class="field">
    <%= form.label :pictures %>
    <%= form.text_field :pictures %>
  </div>

  <div class="field">
    <%= form.label :documents %>
    <%= form.text_field :documents %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

foster_api/app/views/children/edit.html.erb
<h1>Editing Child</h1>

<%= render 'form', child: @child %>

<%= link_to 'Show', @child %> |
<%= link_to 'Back', children_path %>

foster_api/app/views/children/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Children</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Status</th>
      <th>Pictures</th>
      <th>Documents</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @children.each do |child| %>
      <tr>
        <td><%= child.name %></td>
        <td><%= child.status %></td>
        <td><%= child.pictures %></td>
        <td><%= child.documents %></td>
        <td><%= link_to 'Show', child %></td>
        <td><%= link_to 'Edit', edit_child_path(child) %></td>
        <td><%= link_to 'Destroy', child, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Child', new_child_path %>

foster_api/app/views/children/new.html.erb
<h1>New Child</h1>

<%= render 'form', child: @child %>

<%= link_to 'Back', children_path %>

foster_api/app/views/children/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @child.name %>
</p>

<p>
  <strong>Status:</strong>
  <%= @child.status %>
</p>

<p>
  <strong>Pictures:</strong>
  <%= @child.pictures %>
</p>

<p>
  <strong>Documents:</strong>
  <%= @child.documents %>
</p>

<%= link_to 'Edit', edit_child_path(@child) %> |
<%= link_to 'Back', children_path %>

foster_api/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FosterApi</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

foster_api/app/views/messageboards/_form.html.erb
<%= form_with(model: messageboard, local: true) do |form| %>
  <% if messageboard.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(messageboard.errors.count, "error") %> prohibited this messageboard from being saved:</h2>

      <ul>
        <% messageboard.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :subject %>
    <%= form.text_field :subject %>
  </div>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_field :content %>
  </div>

  <div class="field">
    <%= form.label :status %>
    <%= form.text_field :status %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

foster_api/app/views/messageboards/edit.html.erb
<h1>Editing Messageboard</h1>

<%= render 'form', messageboard: @messageboard %>

<%= link_to 'Show', @messageboard %> |
<%= link_to 'Back', messageboards_path %>

foster_api/app/views/messageboards/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Messageboards</h1>

<table>
  <thead>
    <tr>
      <th>Subject</th>
      <th>Content</th>
      <th>Status</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @messageboards.each do |messageboard| %>
      <tr>
        <td><%= messageboard.subject %></td>
        <td><%= messageboard.content %></td>
        <td><%= messageboard.status %></td>
        <td><%= link_to 'Show', messageboard %></td>
        <td><%= link_to 'Edit', edit_messageboard_path(messageboard) %></td>
        <td><%= link_to 'Destroy', messageboard, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Messageboard', new_messageboard_path %>

foster_api/app/views/messageboards/new.html.erb
<h1>New Messageboard</h1>

<%= render 'form', messageboard: @messageboard %>

<%= link_to 'Back', messageboards_path %>

foster_api/app/views/messageboards/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Subject:</strong>
  <%= @messageboard.subject %>
</p>

<p>
  <strong>Content:</strong>
  <%= @messageboard.content %>
</p>

<p>
  <strong>Status:</strong>
  <%= @messageboard.status %>
</p>

<%= link_to 'Edit', edit_messageboard_path(@messageboard) %> |
<%= link_to 'Back', messageboards_path %>